### ISSUE TITLE
Can't upload onto Arduino editor

### ISSUE THREAD

**Issue by IanMumford** [ubidots/ubidots-arduino-yun#6]
Hello,

This is my first post hopefully I'm doing this right. when I try to upload the zip file onto Arduino editor library manager. I get the following error message any help would be appreciated. I'm brand new to Arduino if that has any bearing on the current problem not sure.

Error Showing:

LIBRARIES THAT COULD NOT BE IMPORTED:
[ubidots-arduino-yun] [Xq/LabbP] 400 invalid_request: attribute "name" of response is missing and required, parent: response, attribute: name

**Comment by jotathebest** [comment]
please try to compile one of the examples of the library without adding any kind of code, if you get the same error come back to this thread and let us to know, if not your issue is probably related to this library: [Xq/LabbP] .

**Comment by IanMumford** [comment]
I try to Compile the sendvalue example and it says I need the #include <UbidotsYUN.h>

Here is the error message i get:
./opt/arduino-builder/arduino-builder -compile -core-api-version 10611 -build-path /tmp/585360940/build -hardware opt/arduino-builder/hardware -hardware ./opt/cores -tools opt/arduino-builder/tools -tools ./opt/tools -built-in-libraries opt/libraries/latest -libraries /tmp/585360940/pinned -libraries /tmp/585360940/custom -fqbn Intel:arc32:arduino_101 -build-cache /tmp -logger humantags -verbose=false /tmp/585360940/CosmClientString
/tmp/585360940/CosmClientString/CosmClientString.ino:1:24: fatal error: UbidotsYUN.h: No such file or directory
#include <UbidotsYUN.h>
^
compilation terminated.
exit status 1

**Comment by jotathebest** [comment]
closing as this is not an issue related with the library but with include statement at the user's editor.
